
-- Clear existing schema to ensure clean slate
DROP TABLE IF EXISTS telemetry;
DROP TABLE IF EXISTS drives;
DROP TABLE IF EXISTS charges;

-- 1. Telemetry Table: Real-time mapping of OVMS/i3 metrics
CREATE TABLE telemetry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  vehicle_id TEXT NOT NULL,
  timestamp BIGINT NOT NULL,
  
  -- Battery & Electrical
  soc FLOAT,                 -- v.b.soc (%)
  soh FLOAT,                 -- v.b.soh (%)
  voltage FLOAT,             -- v.b.voltage (V)
  current FLOAT,             -- v.b.current (A)
  power FLOAT,               -- v.b.power (kW)
  range_est FLOAT,           -- xi3.v.b.range.bc (km)
  
  -- 12V System
  voltage_12v FLOAT,         -- v.b.12v.voltage
  current_12v FLOAT,         -- v.b.12v.current
  
  -- Charging
  charge_pilot_a FLOAT,      -- xi3.v.c.pilotsignal
  charge_plug_status TEXT,   -- xi3.v.c.chargeplugstatus
  
  -- Driving & Performance
  speed FLOAT,               -- v.p.speed
  odometer FLOAT,            -- v.p.odometer
  motor_rpm FLOAT,           -- v.m.rpm
  consumption_inst FLOAT,    -- v.b.consumption (Wh/km)
  
  -- Trip Stats
  trip_distance FLOAT,       -- v.p.trip
  trip_consumption FLOAT,    -- xi3.v.p.tripconsumption
  trip_energy FLOAT,         -- v.b.energy.used
  
  -- GPS & Location
  latitude FLOAT,            
  longitude FLOAT,           
  elevation FLOAT,           -- v.p.altitude
  location_name TEXT,        -- v.p.location
  gps_sats INT,              -- v.p.satcount
  gps_quality FLOAT,         -- v.p.gpssq
  
  -- Temperatures
  temp_battery FLOAT,        -- v.b.temp
  temp_motor FLOAT,          -- v.m.temp
  temp_ambient FLOAT,        -- v.e.temp
  inside_temp FLOAT,         -- v.e.cabintemp
  charger_temp FLOAT,        -- v.c.temp
  
  -- Climate & Status
  vent_mode TEXT,            -- v.e.cabinintake
  ac_status BOOLEAN,         -- v.e.cooling
  locked BOOLEAN,            -- v.e.locked
  car_on BOOLEAN,            -- v.e.on
  gear TEXT,                 -- v.e.gear
  park_time FLOAT,           -- v.e.parktime
  drive_time FLOAT,          -- v.e.drivetime
  last_update_age FLOAT,     -- xi3.s.age
  
  -- Doors
  door_fl BOOLEAN,
  door_fr BOOLEAN,
  door_rl BOOLEAN,
  door_rr BOOLEAN,
  door_hood BOOLEAN,
  door_trunk BOOLEAN,
  door_cp BOOLEAN,
  
  -- Raw Data
  raw_metrics JSONB,
  car_metrics JSONB
);

CREATE INDEX idx_telemetry_vid_ts ON telemetry (vehicle_id, timestamp DESC);

-- 2. Drives Table
CREATE TABLE drives (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  vehicle_id TEXT NOT NULL,
  start_date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ,
  distance FLOAT,            -- km
  duration FLOAT,            -- min
  start_soc FLOAT,
  end_soc FLOAT,
  consumption FLOAT,         -- kWh
  efficiency FLOAT,          -- Wh/km
  path JSONB                 -- Array of {lat, lng, speed, soc}
);

-- 3. Charges Table
CREATE TABLE charges (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  vehicle_id TEXT NOT NULL,
  date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ,
  location TEXT,
  latitude FLOAT,
  longitude FLOAT,
  start_soc FLOAT,
  end_soc FLOAT,
  added_kwh FLOAT,
  duration FLOAT,            -- min
  avg_power FLOAT,           -- kW
  max_power FLOAT,           -- kW
  chart_data JSONB           -- Array of {time, power, soc}
);

-- RLS & Permissions
ALTER TABLE telemetry ENABLE ROW LEVEL SECURITY;
ALTER TABLE drives ENABLE ROW LEVEL SECURITY;
ALTER TABLE charges ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read" ON telemetry FOR SELECT USING (true);
CREATE POLICY "Public Insert" ON telemetry FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Read Drives" ON drives FOR SELECT USING (true);
CREATE POLICY "Public Insert Drives" ON drives FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Drives" ON drives FOR UPDATE USING (true);
CREATE POLICY "Public Read Charges" ON charges FOR SELECT USING (true);
CREATE POLICY "Public Insert Charges" ON charges FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Charges" ON charges FOR UPDATE USING (true);
