-- ⚠️ WARNING: THIS SCRIPT WILL DELETE ALL EXISTING DATA ⚠️
-- Run this in Supabase Dashboard -> SQL Editor to reset and fix your database schema.

-- 1. CLEANUP
DROP TABLE IF EXISTS telemetry;
DROP TABLE IF EXISTS drives;
DROP TABLE IF EXISTS charges;

-- 2. TELEMETRY TABLE (High frequency data)
CREATE TABLE telemetry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  vehicle_id TEXT NOT NULL,
  timestamp BIGINT NOT NULL, -- Unix timestamp (ms)
  
  -- Core Battery & Range
  soc FLOAT,                 
  soh FLOAT,                 -- State of Health
  capacity FLOAT,            -- Usable capacity (kWh)
  range FLOAT,               -- General range
  est_range FLOAT,           
  ideal_range FLOAT,         
  
  -- Electrical
  voltage FLOAT,             
  current FLOAT,             
  power FLOAT,               
  voltage_12v FLOAT,         -- Aux battery
  current_12v FLOAT,         
  
  -- Charging Session (Instant)
  charge_state TEXT,         
  charge_mode TEXT,          -- standard, range, performance
  charge_kwh FLOAT,          -- Energy added this session
  charge_time FLOAT,         -- Duration
  charge_temp FLOAT,         -- Charger temp
  charge_pilot BOOLEAN,      -- Pilot signal present
  charge_limit_soc FLOAT,
  charge_limit_range FLOAT,
  charge_type TEXT,          -- type2, ccs, etc.

  -- Driving & Location
  speed FLOAT,               
  odometer FLOAT,            
  latitude FLOAT,
  longitude FLOAT,
  elevation FLOAT,
  direction FLOAT,           -- Bearing
  gps_lock BOOLEAN,
  gps_sats INT,
  location_name TEXT,
  
  -- Temperatures
  temp_battery FLOAT,        
  temp_motor FLOAT,          
  temp_ambient FLOAT,
  inside_temp FLOAT,         
  outside_temp FLOAT,        
  
  -- Status / State
  locked BOOLEAN,
  valet BOOLEAN,
  car_awake BOOLEAN,
  gear TEXT,                 -- D, P, R, N
  handbrake BOOLEAN,
  
  -- TPMS (Bar/Psi/kPa)
  tpms_fl FLOAT,
  tpms_fr FLOAT,
  tpms_rl FLOAT,
  tpms_rr FLOAT,
  
  -- Raw Data Storage
  -- 1. Standard OVMS metrics (v.*) that don't have their own column
  raw_metrics JSONB,
  
  -- 2. Vehicle Specific metrics (xi3.*, leaf.*, etc.)
  car_metrics JSONB
);

CREATE INDEX idx_telemetry_vid_ts ON telemetry (vehicle_id, timestamp DESC);

-- 3. DRIVES TABLE (Sessions)
CREATE TABLE drives (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  vehicle_id TEXT NOT NULL,
  start_date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ,
  
  distance FLOAT,            -- km
  duration FLOAT,            -- minutes
  
  start_soc FLOAT,
  end_soc FLOAT,
  start_odometer FLOAT,
  end_odometer FLOAT,
  
  consumption FLOAT,         -- kWh
  efficiency FLOAT,          -- Wh/km
  
  path JSONB                 -- Simplified path for UI
);

CREATE INDEX idx_drives_start_date ON drives (start_date DESC);

-- 4. CHARGES TABLE (Sessions)
CREATE TABLE charges (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  vehicle_id TEXT NOT NULL,
  date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ,
  
  location TEXT,
  added_kwh FLOAT,
  duration FLOAT,            -- minutes
  
  start_soc FLOAT,
  end_soc FLOAT,
  
  avg_power FLOAT,
  max_power FLOAT,
  
  chart_data JSONB
);

CREATE INDEX idx_charges_date ON charges (date DESC);

-- 5. ROW LEVEL SECURITY
ALTER TABLE telemetry ENABLE ROW LEVEL SECURITY;
ALTER TABLE drives ENABLE ROW LEVEL SECURITY;
ALTER TABLE charges ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable read access for all users" ON telemetry FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON telemetry FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON drives FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON drives FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON drives FOR UPDATE USING (true);

CREATE POLICY "Enable read access for all users" ON charges FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON charges FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON charges FOR UPDATE USING (true);

-- 6. Refresh Schema Cache
NOTIFY pgrst, 'reload schema';