
-- Update: Added park_time column
-- You can run this line in Supabase SQL editor if table already exists:
-- ALTER TABLE telemetry ADD COLUMN park_time FLOAT;

DROP TABLE IF EXISTS telemetry;
DROP TABLE IF EXISTS drives;
DROP TABLE IF EXISTS charges;

CREATE TABLE telemetry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  vehicle_id TEXT NOT NULL,
  timestamp BIGINT NOT NULL,
  soc FLOAT,                 
  soh FLOAT,                 
  capacity FLOAT,            
  range FLOAT,               
  est_range FLOAT,           
  ideal_range FLOAT,         
  voltage FLOAT,             
  current FLOAT,             
  power FLOAT,               
  voltage_12v FLOAT,         
  current_12v FLOAT,         
  charge_state TEXT,         
  charge_mode TEXT,          
  charge_kwh FLOAT,          
  charge_time FLOAT,         
  charge_temp FLOAT,         
  charge_pilot BOOLEAN,      
  charge_limit_soc FLOAT,
  charge_limit_range FLOAT,
  charge_type TEXT,          
  speed FLOAT,               
  odometer FLOAT,            
  latitude FLOAT,
  longitude FLOAT,
  elevation FLOAT,
  direction FLOAT,           
  gps_lock BOOLEAN,
  gps_sats INT,
  location_name TEXT,
  temp_battery FLOAT,        
  temp_motor FLOAT,          
  temp_ambient FLOAT,
  inside_temp FLOAT,         
  outside_temp FLOAT,        
  locked BOOLEAN,
  valet BOOLEAN,
  car_awake BOOLEAN,
  gear TEXT,                 
  handbrake BOOLEAN,
  park_time FLOAT, -- ADDED
  tpms_fl FLOAT,
  tpms_fr FLOAT,
  tpms_rl FLOAT,
  tpms_rr FLOAT,
  raw_metrics JSONB,
  car_metrics JSONB
);

CREATE INDEX idx_telemetry_vid_ts ON telemetry (vehicle_id, timestamp DESC);

CREATE TABLE drives (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  vehicle_id TEXT NOT NULL,
  start_date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ,
  distance FLOAT,            
  duration FLOAT,            
  start_soc FLOAT,
  end_soc FLOAT,
  start_odometer FLOAT,
  end_odometer FLOAT,
  consumption FLOAT,         
  efficiency FLOAT,          
  path JSONB                 
);

CREATE INDEX idx_drives_start_date ON drives (start_date DESC);

CREATE TABLE charges (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  vehicle_id TEXT NOT NULL,
  date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ,
  location TEXT,
  added_kwh FLOAT,
  duration FLOAT,            
  start_soc FLOAT,
  end_soc FLOAT,
  avg_power FLOAT,
  max_power FLOAT,
  chart_data JSONB
);

CREATE INDEX idx_charges_date ON charges (date DESC);

ALTER TABLE telemetry ENABLE ROW LEVEL SECURITY;
ALTER TABLE drives ENABLE ROW LEVEL SECURITY;
ALTER TABLE charges ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON telemetry FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON telemetry FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable read access for all users" ON drives FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON drives FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON drives FOR UPDATE USING (true);
CREATE POLICY "Enable read access for all users" ON charges FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON charges FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON charges FOR UPDATE USING (true);

NOTIFY pgrst, 'reload schema';
